name: TicketApp CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # 1. Checkout Code
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -----------------------------
      # 2. Log in to Docker Hub
      # -----------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------------
      # 3. Set image tags
      # -----------------------------
      - name: Set up tags
        id: vars
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "API_IMAGE=ashokm2602/ticketapp-api" >> $GITHUB_ENV
          echo "FRONT_IMAGE=ashokm2602/ticketapp-frontend" >> $GITHUB_ENV

      # -----------------------------
      # 4. Build Backend (API)
      # -----------------------------
      - name: Build API Docker Image
        run: |
          docker build -t $API_IMAGE:latest -t $API_IMAGE:${SHA} ./TicketApp

      # -----------------------------
      # 5. Build Frontend
      # -----------------------------
      - name: Build Frontend Docker Image
        run: |
          docker build -t $FRONT_IMAGE:latest -t $FRONT_IMAGE:${SHA} ./TicketApp-frontend

      # -----------------------------
      # 6. Push backend image
      # -----------------------------
      - name: Push API Image
        run: |
          docker push $API_IMAGE:latest
          docker push $API_IMAGE:${SHA}

      # -----------------------------
      # 7. Push frontend image
      # -----------------------------
      - name: Push Frontend Image
        run: |
          docker push $FRONT_IMAGE:latest
          docker push $FRONT_IMAGE:${SHA}
